### PR TITLE
Fixes for TruffleRuby and add TruffleRuby in CI

### PR DESCRIPTION
**Pull request by eregon**
See the individual commits for details.

Needs https://github.com/oracle/truffleruby/pull/3400 for the truffleruby-head job to pass the test suite.
(it can already be merged though, as you prefer)

### CODE REVIEW

**Comment by casperisfine** [comment]
Seems to be missing some more checks: `symbol lookup error: /home/runner/work/liquid-c/liquid-c/lib/liquid_c.so: undefined symbol: rb_check_funcall`

**Comment by casperisfine** [comment]
Nevermind, you mentioned it 🤦

**Comment by eregon** [comment]
@casperisfine or @nirvdrum Could you rerun https://github.com/Shopify/liquid-c/actions/runs/7615407078/job/20739862301 ? The `rb_check_funcall` PR got merged so if rerun the tests should pass and we can track if it goes red with https://github.com/eregon/truffleruby-gem-tracker.

**Comment by casperisfine** [comment]
> Could you rerun

Done: https://github.com/Shopify/liquid-c/actions/runs/7615407078/job/20764127709

> I know this might be a big ask, but would it be possible to make a release including these fixes?

Hum, it's a bit tricky. Our team doesn't really handle that gem. It's OK for us to merge pure compatibilty patches, but cutting a release is over stepping a bit. I'll try to track down the owners and ask.

**Comment by casperisfine** [comment]
4.2.0 is out: https://rubygems.org/gems/liquid-c/versions/4.2.0

**Comment by eregon** [comment]
Thank you!

**Pull request merged**
